// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"ai-chat-sql/internal/dao/internal"
)

// databaseConfDao is the data access object for the table database_conf.
// You can define custom methods on it to extend its functionality as needed.
type databaseConfDao struct {
	*internal.DatabaseConfDao
}

var (
	// DatabaseConf is a globally accessible object for table database_conf operations.
	DatabaseConf = databaseConfDao{internal.NewDatabaseConfDao()}
)

// Add your custom methods and functionality below.
