// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package ai_chat

import (
	"ai-chat-sql/api/ai_chat"
)

type ControllerV1 struct{}

func NewV1() ai_chat.IAiChatV1 {
	return &ControllerV1{}
}
